### ISSUE TITLE
Warning: No runtime manager found for Lab 04 Async Process Job Execution

### ISSUE THREAD

**Issue by diego-torres** [gpe-mw-training/advanced-process-development-labs#2]
2017-03-20 15:26:32,552 WARN  [org.jbpm.executor.impl.AbstractAvailableJobsExecutor] (EJB default - 10) Error during command org.jbpm.proces
s.core.async.AsyncSignalEventCommand error message No runtime manager found for deployment id com.redhat.gpte.bpms-advanced:async-lab-proces
s-kjar:2.0: java.lang.IllegalArgumentException: No runtime manager found for deployment id com.redhat.gpte.bpms-advanced:async-lab-process-k
jar:2.0
        at org.jbpm.process.core.async.AsyncSignalEventCommand.execute(AsyncSignalEventCommand.java:42)
        at org.jbpm.executor.impl.AbstractAvailableJobsExecutor.executeGivenJob(AbstractAvailableJobsExecutor.java:122)
        at org.jbpm.executor.impl.AvailableJobsExecutor.executeJob(AvailableJobsExecutor.java:38)
        at org.kie.server.jms.executor.PollExecutorBean.executeJob(PollExecutorBean.java:84)
        at sun.reflect.GeneratedMethodAccessor185.invoke(Unknown Source)

**Comment by btison** [comment]
This warning comes from the fact that both Business-Central as KIE-Server are pointing to the same database. The executor module form KIE server picks up a job created by a deployment on Business-Central. As KIE-Server does not have this deployment, it cannot execute the job and issues this warning.
In the context of the course labs, the workaround is to undeploy KIE-server while doing the Lab 04 Async Process Job Execution lab.
